# AutoMate/.github/workflows/automate-ai.yml

name: AutoMate AI Workflow

on:
  workflow_call:  # Enables external repos to call this workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_automate_ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AutoMate code
        uses: actions/checkout@v3  # Ensure AutoMate’s code is checked out

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run Organiser
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTOMATE_GITHUB_TOKEN: ${{ secrets.AUTOMATE_GITHUB_TOKEN }}
        run: |
          python scripts/Organiser.py
