name: AutoMate AI Workflow

on:
  workflow_call:  # Enables the workflow to be called by other workflows
  workflow_dispatch:  # Allows you to manually trigger the workflow
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on PR to the main branch

jobs:
  run_automate_ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code from the repo

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up Python environment
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Code Checker
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Uses the secret API key
        run: |
          python scripts/code_checker.py
