name: AutoMate AI Workflow

on:
  workflow_call:  # Enables external repos to call this workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_automate_ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Code Checker
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Secret stays in AutoMate
        run: |
          python scripts/code_checker.py
